# **Análise de Dados no Varejo com NumPy**

**Nível 1 - Básico**

In [1]:
import numpy as np

print('Versão do NumPy:', np.__version__)


Versão do NumPy: 2.1.3


In [8]:
pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])

dias_de_pico = pecas_vendidas > 200

print("Dias de pico:",pecas_vendidas[dias_de_pico])

estimativa_faturamento = pecas_vendidas * 50

print("Estimativa de faturamento durante a semana:",estimativa_faturamento)

Dias de pico: [210 300 250]
Estimativa de faturamento durante a semana: [ 7500  6000  4500 10500 15000 12500  9000]


**Nível 2 - Intermediário**

In [16]:
vendas_filiais = np.array([[200, 220, np.nan, 250], [150, 180, 160, 190], [300, 310, 290, 330]])

print("Vendas por filial:", np.nansum(vendas_filiais, axis=1))
print("Media diaria das vendas:", np.nanmean(vendas_filiais))
indicador_meta = np.where(vendas_filiais > 200, "Meta atingida", "Abaixo")
print(indicador_meta)

Vendas por filial: [ 670.  680. 1230.]
Media diaria das vendas: 234.54545454545453
[['Abaixo' 'Meta atingida' 'Abaixo' 'Meta atingida']
 ['Abaixo' 'Abaixo' 'Abaixo' 'Abaixo']
 ['Meta atingida' 'Meta atingida' 'Meta atingida' 'Meta atingida']]


**Nível 3 - Avancado**

In [18]:
rng = np.random.default_rng()
amostras = rng.choice(["Eletronicos", "Roupas", "Casa"], size=50)
unicos, contagens = np.unique(amostras, return_counts=True)
print('valores únicos:', unicos)
print('contagens     :', contagens)

valores únicos: ['Casa' 'Eletronicos' 'Roupas']
contagens     : [18 17 15]


In [21]:
faturamento_campanhas = np.array([12000, 45000, 23000, 89000, 31000])
print("Maior faturamento:", faturamento_campanhas.argmax())
print("Valor do maior faturamento:", faturamento_campanhas.max())

Maior faturamento: 3
Valor do maior faturamento: 89000


# **Organização e Transformação de Dados com NumPy**

**Nível 1 - Básico**

In [33]:
mes_faturamento = np.arange(1,31)
print('arr[::-1]:', mes_faturamento[::-1][:5], '(invertido)')

simulacao__vendas = np.linspace(20000, 30000, 5)
print(simulacao__vendas)

contagem_estoque = np.array([10.5, 20.1, 30.9])
contagem_estoque = contagem_estoque.astype(int)
print(contagem_estoque)

arr[::-1]: [30 29 28 27 26] (invertido)
[20000. 22500. 25000. 27500. 30000.]
[10 20 30]


**Nível 2 - Intermediario**

In [34]:
total_visitas = np.array([33, 55, 400, 56, 77, 76, 200, 50, 95, 180, 45, 98])
total_visitas_trimestre = total_visitas.reshape(4,3)
print(total_visitas_trimestre)

[[ 33  55 400]
 [ 56  77  76]
 [200  50  95]
 [180  45  98]]


In [44]:
primeiro_semestre = np.array([100, 600, 400, 500, 700, 760])
segundo_semestre = np.array([400, 200, 100, 560, 780, 940])

ano_completo = np.vstack((primeiro_semestre, segundo_semestre))
print("Ano completo:",ano_completo)

primeiro_trimestre = ano_completo[0,0:3].copy()
print("Dados do primeiro trimestre",primeiro_trimestre)

ano_completo = ano_completo.ravel()
print("Ano completo achatado em 1D:",ano_completo)

Ano completo: [[100 600 400 500 700 760]
 [400 200 100 560 780 940]]
Dados do primeiro trimestre [100 600 400]
Ano completo achatado em 1D: [100 600 400 500 700 760 400 200 100 560 780 940]


**Nível 3: Avançado**

In [45]:
pontuacoes = np.array([85, 92, 78, 95, 88])

indices = np.argsort(pontuacoes)

print("Índices da ordenação:", indices)

Índices da ordenação: [2 0 4 1 3]


In [48]:
precos = np.array([100, 200, 300])
precos_coluna = precos[:, np.newaxis]
descontos = np.array([0.10, 0.15, 0.20])

precos_com_desconto = precos_coluna * (1 - descontos)

print(precos_com_desconto)

[[ 90.  85.  80.]
 [180. 170. 160.]
 [270. 255. 240.]]


In [49]:
A = np.array([
    [2, 1],
    [1, -1]
])

b = np.array([500, 100])

precos = np.linalg.solve(A, b)

print("Preço da placa:", precos[0])
print("Preço do sensor:", precos[1])

Preço da placa: 200.0
Preço do sensor: 100.0
